### ISSUE TITLE
ERR_MODULE_NOT_FOUND after update to 0.6.1

### ISSUE THREAD

**Issue by hayden-donnelly** [sfcompute/cli#88]
I can't run any commands after updating to 0.6.1, they all give the following error:
```
error: [ERR_MODULE_NOT_FOUND] Cannot find module 'file:///tmp/deno-compile-sf/node_modules/semver/index.js' imported from 'file:///tmp/deno-compile-sf/src/checkVersion.ts'
```

OS: Ubuntu 22.04.5 LTS x86_64

**Comment by hayden-donnelly** [comment]
Fixed on 0.6.4
